apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: dhiv123/kubernetes:latest
          imagePullPolicy: Always